# API Gateway Router Configuration
http:
  routers:
    api-gateway:
      entryPoints:
        - websecure
      rule: "Host(`api.sj-cloud.test`) || Host(`api.test`)"
      service: platform-noop
      tls: {}
      middlewares:
        - security-headers
        - global-rate-limit
