# TLS Stores Configuration
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certificates/development/platform.test.crt"
        keyFile: "/etc/traefik/certificates/development/platform.test.key"
