const EventTypes = {
  SERVICE_REGISTERED: 'SERVICE_REGISTERED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  SERVICE_REMOVED: 'SERVICE_REMOVED',
  SNAPSHOT_COMPILED: 'SNAPSHOT_COMPILED',
  SNAPSHOT_ACTIVATED: 'SNAPSHOT_ACTIVATED',
  SNAPSHOT_ROLLED_BACK: 'SNAPSHOT_ROLLED_BACK',
  REGISTRY_RELOADED: 'REGISTRY_RELOADED',
  HEALTH_CHANGED: 'HEALTH_CHANGED',
  CIRCUIT_OPENED: 'CIRCUIT_OPENED',
  CIRCUIT_CLOSED: 'CIRCUIT_CLOSED',
  CIRCUIT_HALF_OPEN: 'CIRCUIT_HALF_OPEN',
  ROUTING_POLICY_CHANGED: 'ROUTING_POLICY_CHANGED'
};

module.exports = EventTypes;
